### PR TITLE
acquire data on latest block

### PR DESCRIPTION
**Pull request by wakamex**

### CODE REVIEW

**Review by dpaiton — APPROVED** [review]
👍

**Review by dpaiton — CHANGES_REQUESTED** [review]
Requesting a review from Sheng, since I am now realizing that the `-1` was probably on purpose.

**Comment by slundqui** [comment]
Requesting a review from @sentilesdal, since it was a conversation with him that suggested we shouldn't assume the most current block is fixed. Although, we should look into if the block is only queryable after it's mined.

**Comment by wakamex** [comment]
discussion continued in #801 
merged into my testing branch at https://github.com/wakamex/elf-simulations

**Pull request closed without merging**
